# DiscordのWebhook URLを設定します。
# 複数のURLを設定することができます。
DISCORD_WEBHOOK_URL:
  - "https://discord.com/api/webhooks/"

# 起動時にメッセージで通知するかどうかを設定します。
FIRST_MESSAGE: true

# ================================

# QiitaのRSSフィードのURLを設定します。
# 複数のURLを設定することができます。
QIITA_RSS_URL:
  - "https://qiita.com/example/activities.atom"

# RSSの更新を検知する間隔を秒で設定します。
INTERVAL: 600
